---
- name: d13-mariadbserver
  become: yes
  hosts: d13-mariadbserver

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_databases: true

    - name: Instala Mysql e cria dbs/users
      include_role:
        name: geerlingguy.mysql
      vars:
        mysql_packages:
          - mariadb-client
          - mariadb-server
        mysql_daemon: mariadb
        mysql_root_username: root
        mysql_root_password: "SuperPassw0rd"
        mysql_bind_address: '*'
        mysql_mysqldump_max_allowed_packet: "1024M"
